# handler paths are relative to the root serverless.yml file that this is being merged into
# they are also compiled by babel into a 'dist' folder at the root
list:
  handler: src/handlers/offers/list.handler
  events:
    - http: get /v1/offers/
get:
  handler: src/handlers/offers/get.handler
  events:
    - http: get /v1/offers/{offerId}

add-location:
  handler: src/handlers/offers/add-location.handler
  events:
    - http: post /v1/offers/{offerId}/locations/{locationId}

